# Generated by Django 4.0.2 on 2022-02-08 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todos',
            name='is_complated',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
