# Generated by Django 4.0.2 on 2022-02-09 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_alter_todos_is_complated'),
    ]

    operations = [
        migrations.AddField(
            model_name='todos',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
