# Generated by Django 4.0.2 on 2022-02-10 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_todos_updated_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='todos',
            options={'ordering': ['-updated_at', '-created_at']},
        ),
    ]
